version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:              
    image: percona 
    restart: always
#    volumes:
#      - ./data/db:/var/lib/mysql
    env_file:      
      - ./build/env

  mage:
    build:
      context: ./build
      dockerfile: apache
    restart: always
    hostname: mage
#    volumes:
#      - ./data/www/mage:/var/www/html
    env_file:
      - ./build/env
